### ISSUE TITLE
What is the meaning of control type for command powercap-set？

### ISSUE THREAD

**Issue by xfhelen** [energymon/energymon#38]
I am not clear what the meaning of control type for command powercap-set is？
What are its choices. Such as for --zone=ZONES, the range of ZONES includes PACKAGE, CORE, UNCORE,etc.

**Comment by connorimes** [comment]
You're getting projects mixed up - energymon doesn't do anything with power capping.  I think you're asking about the powercap project at https://github.com/powercap/powercap .  The `powercap-set` command is a generic interface to the `powercap` control types exposed by the kernel at `/sys/class/powercap`.  AFAIK, `intel-rapl` is the only supported control type.  See the kernel documentation on powercap: https://www.kernel.org/doc/Documentation/power/powercap/powercap.txt

`powercap-set` isn't really intended to be used -- your life would be simpler if you used the `rapl-set` command instead.  Note, though, that even `rapl-set` deals with zones by index numbers exactly as they are exposed by the powercap interface in sysfs.  See the output of `rapl-info` and check the man pages to see examples and further documentation: `man rapl-info` and `man rapl-set`.

To manage zones by name, you want to use the abstractions provided by `rapl-configure-*` binaries in the `raplcap` project at https://github.com/powercap/raplcap .  I think we sorted this out over email.  In the future, let's please discuss questions over email instead of opening issues (unless there is actually a bug in the software).  Cheers.
