### ISSUE TITLE
Bug in elapsed time calculation

### ISSUE THREAD

**Issue by jasonm128** [energymon/energymon#40]
There is a bug in either the microsecond versions of the ptime routines or in the way that they are used by the sensor-polling threads in the odroid, odroid-ioctl, osp, wattsup and zcu102 implementations.  I can't tell which is incorrect because the function descriptions in common/ptime/ptime.h are a bit vague.  Specifically, they don't say what the units are for the `since` argument in any of the routines.  Right now, both the `_ns` and `_us` versions of the routines treat `since` as if it is in nanoseconds.  However, the polling routines capture an initial time in microseconds and then pass that to `energymon_gettime_elapsed_us` which passes it to `ptime_gettime_elapsed_us`.  Thus the first elapsed time calculation is incorrect and therefore the first energy calculation is incorrect.  The elapsed time routines update `since` with a time in nanoseconds so it works correctly for subsequent invocations and the difference between two energy readings will be correct but the total is not.

You can see this problem by running the interval_test.  Here's the output on a zcu102 compiled with ENERGYMON_DEBUG=1:
```
jasonm@ubuntu:~/energymon_github/_build64$ test/interval-test 100000
Initializing reading from ZCU102 INA226 Power Sensors
zcu102_poll_sensors: Read total power: 3025000 uW (3.025000 W)
zcu102_poll_sensors: Calculated energy: 3.025000 W * 6200404583720 us = 18756223865753 uJ
zcu102_poll_sensors: Read total power: 3025000 uW (3.025000 W)
zcu102_poll_sensors: Calculated energy: 3.025000 W * 7159 us = 21655 uJ
zcu102_poll_sensors: Read total power: 3025000 uW (3.025000 W)
zcu102_poll_sensors: Calculated energy: 3.025000 W * 35018 us = 105929 uJ
zcu102_poll_sensors: Read total power: 3000000 uW (3.000000 W)
zcu102_poll_sensors: Calculated energy: 3.000000 W * 7188 us = 21564 uJ
Start energy: 0 uJ   End energy: 18756224014901 uJ
Total energy: 18756224014901 uJ
Average power: 187562240.149010 W
Finished reading from ZCU102 INA226 Power Sensors
```

I'm happy to fix this if I can get clarification on whether the `since` argument for `energymon_gettime_elapsed_us` and `ptime_gettime_elapsed_us` is supposed to be in microseconds or nanoseconds.

**Comment by connorimes** [comment]
Nice catch, I haven't touched the odroid or related code in quite some time, and the ptime stuff is newer.

The `since` argument should be the same units as the function name indicates and returns, so this is a bug in the ptime code.  It should probably be renamed to `since_ns` and `since_us` as appropriate.  The ptime name is just b/c I broke that code out into a separate project for testing - https://github.com/connorimes/portable_time
So the updated function should probably be more like:
```C
uint64_t ptime_gettime_elapsed_us(ptime_clock_id clk_id, uint64_t* since) {
  uint64_t ret = ptime_gettime_elapsed_ns(clk_id, since) / (uint64_t) ONE_THOUSAND;
  *since /= (uint64_t) ONE_THOUSAND;
  return ret;
}
```
Ideally what I'd do is fix this in the `portable_time` project and add appropriate tests as the current ones I hacked together are clearly insufficient.  I won't have time to do any of this until next week, but don't expect you to do anything with `portable_time`.  You can go ahead and fix this in energymon and I will merge the PR when I get a chance.  Thanks, it's great having another set of eyes on this codebase.

**Comment by connorimes** [comment]
Also, I was in the process of tagging a new release to push to the MIT repo.  I'll delete it from my fork (since I haven't pushed it here yet), and we'll include this timing fix in the new release before pushing the  tag here and to the MIT repo (along with `master`).

**Comment by jasonm128** [comment]
Actually it's a little worse than that.  If we want to use `ptime_gettime_elapsed_ns` internally, the new code would need to be:
```c
uint64_t ptime_gettime_elapsed_us(ptime_clock_id clk_id, uint64_t* since) {
  *since *= (uint64_t) ONE_THOUSAND;
  uint64_t ret = ptime_gettime_elapsed_ns(clk_id, since) / (uint64_t) ONE_THOUSAND;
  *since /= (uint64_t) ONE_THOUSAND;
  return ret;
}
```
That's an extra multiplication and two extra divisions vs. the ns version.  We could do it much more efficiently if we implemented it from scratch instead of calling `ptime_gettime_elapsed_ns`.  It would look just like `ptime_gettime_elapsed_ns` except that it would call `ptime_gettime_us`:
```c
uint64_t ptime_gettime_elapsed_us(ptime_clock_id clk_id, uint64_t* since) {
  uint64_t now;
  uint64_t elapsed;
  if (!(now = ptime_gettime_us(PTIME_MONOTONIC))) {
    return 0;
  }
  if (*since > now) {
    errno = EINVAL;
    return 0;
  }
  elapsed = now - *since;
  *since = now;
  return elapsed;
}
```
I know you probably don't want to have duplicate code but it saves a multiplication and a division (plus the related loads and stores).  What do you think?  I suppose another alternative is to introduce a helper function or macro for the duplicate code.

**Comment by connorimes** [comment]
Naturally I realize in the middle of the night that my suggestion above is also incorrect in that it doesn't update `since` before passing to the nanosecond function.  It's probably easier to just re-implement `ptime_gettime_elapsed_us` without wrapping around `ptime_gettime_elapsed_ns`, otherwise we have just as many temp variables.  I'm still out of town at a family even though, so I can't fix it myself yet.

**Comment by connorimes** [comment]
I pushed changes to `portable_time` but don't have a way to test the integration in energymon right now (or even reproduce this bug to start with) since I don't have access to a system that requires polling power sensors.  If you need a fix now, you can test out what I pushed there (just copy/paste the .c and .h file over).

**Comment by jasonm128** [comment]
It's not an emergency for me but I'll try to fix it and test today so we
can move on.



On Nov 18, 2017 10:40 AM, "Connor Imes" <notifications@github.com> wrote:

I pushed changes to portable_time but don't have a way to test the
integration in energymon right now (or even reproduce this bug to start
with) since I don't have access to a system that requires polling power
sensors. If you need a fix now, you can test out what I pushed there (just
copy/paste the .c and .h file over).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/energymon/energymon/issues/40#issuecomment-345450221>,
or mute the thread
